name: dart_orm_docker_test
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  orm: 4.0.0-beta.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
